dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
    - libspdlog-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- doxygen Doxyfile

deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -unik3991:${BINTRAY_API_KEY} "https://api.bintray.com/content/nik3991/otus_p/homework/${TRAVIS_BUILD_NUMBER}/print_ip-0.0.${TRAVIS_BUILD_NUMBER}-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"

deploy:
  provider: pages
  local_dir: docs/html
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master